config/routes.rb
Rails.application.routes.draw do
  resources :facts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fact.rb
class Fact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
  before_action :set_fact, only: %i[ show edit update destroy ]

  # GET /facts or /facts.json
  def index
    @facts = Fact.all
  end

  # GET /facts/1 or /facts/1.json
  def show
  end

  # GET /facts/new
  def new
    @fact = Fact.new
  end

  # GET /facts/1/edit
  def edit
  end

  # POST /facts or /facts.json
  def create
    @fact = Fact.new(fact_params)

    respond_to do |format|
      if @fact.save
        format.html { redirect_to fact_url(@fact), notice: "Fact was successfully created." }
        format.json { render :show, status: :created, location: @fact }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /facts/1 or /facts/1.json
  def update
    respond_to do |format|
      if @fact.update(fact_params)
        format.html { redirect_to fact_url(@fact), notice: "Fact was successfully updated." }
        format.json { render :show, status: :ok, location: @fact }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @fact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /facts/1 or /facts/1.json
  def destroy
    @fact.destroy

    respond_to do |format|
      format.html { redirect_to facts_url, notice: "Fact was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fact
      @fact = Fact.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def fact_params
      params.require(:fact).permit(:character, :droid, :planet, :quote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/views/facts/_fact.html.erb
  <tr>
    <td>
      <%= fact.character %>
    </td>

    <td>
      <%= fact.droid %>
    </td>

    <td>
      <%= fact.planet %>
    </td>

    <td>
      <%= fact.quote %>
    </td>
    <td>
      <%= link_to "Show this fact", fact %>
    </td>
  </tr>

app/views/facts/_form.html.erb
<%= form_with(model: fact) do |form| %>
  <% if fact.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(fact.errors.count, "error") %> prohibited this fact from being saved:</h2>

      <ul>
        <% fact.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :character, style: "display: block" %>
    <%= form.text_field :character %>
  </div>

  <div>
    <%= form.label :droid, style: "display: block" %>
    <%= form.text_field :droid %>
  </div>

  <div>
    <%= form.label :planet, style: "display: block" %>
    <%= form.text_field :planet %>
  </div>

  <div>
    <%= form.label :quote, style: "display: block" %>
    <%= form.text_field :quote %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/facts/edit.html.erb
<h1>Editing fact</h1>

<%= render "form", fact: @fact %>

<br>

<div>
  <%= link_to "Show this fact", @fact %> |
  <%= link_to "Back to facts", facts_path %>
</div>

app/views/facts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Facts</h1>
<%= link_to "New fact", new_fact_path %>
<div></div>
<hr>
<table class="table is-bordered">
    <tr>
      <td>Character:</td>
      <td>Droid:</td>
      <td>Planet:</td>
      <td>Quote:</td>
      <td></td>
    </tr>

    <% @facts.each do |fact| %>
      <%= render fact %>
    <% end %>
</table>

app/views/facts/new.html.erb
<h1>New fact</h1>

<%= render "form", fact: @fact %>

<br>

<div>
  <%= link_to "Back to facts", facts_path %>
</div>

app/views/facts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @fact %>

<div>
  <%= link_to "Edit this fact", edit_fact_path(@fact) %> |
  <%= link_to "Back to facts", facts_path %>

  <%= button_to "Destroy this fact", @fact, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StarWars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.3/css/bulma-rtl.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <section>
    <%= yield %>
  </section>
  </body>
</html>